#!/usr/bin/env bash
# Display formatted information about users from /etc/passwd

while IFS=":" read -r username password userid groupid info home shell
do
  echo "The user $username is part of the $groupid gang, lives in $home and rides $shell."
  echo "$username's place is protected by the passcode $password, more info about the user here: $info"
done < /etc/passwd
